name: PHP-Prefixer Next

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run PHP-Prefixer
        uses: PHP-Prefixer/php-prefixer-build-action@next-typescript-action
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          repository: ${{ env.GITHUB_REPOSITORY }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}